import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium import webdriver


browser = webdriver.Chrome(executable_path="D:\\Maxence\\Documents\\Code\\Python-Automatation\\selenium-chrome-driver") #Don't forget to change the path
browser.get("https://www.pole-emploi.fr/accueil/")
browser.maximize_window()
browser.implicitly_wait(100)
button = browser.find_element_by_id("footer_tc_privacy_button_2")
button.click()
browser.get("https://authentification-candidat.pole-emploi.fr/connexion/XUI/?realm=%2Findividu&goto=https%3A%2F%2Fauthentification-candidat.pole-emploi.fr%3A443%2Fconnexion%2Foauth2%2Frealms%2Froot%2Frealms%2Findividu%2Fauthorize%3Frealm%3D%252Findividu%26response_type%3Did_token%2520token%26scope%3Dopenid%2520compteUsager%2520profile%2520contexteAuthentification%2520email%2520courrier%2520notifications%2520etatcivil%2520logW%2520individu%2520pilote%2520nomenclature%2520coordonnees%2520navigation%2520reclamation%2520prdvl%2520idIdentiteExterne%2520pole_emploi%2520suggestions%2520actu%2520application_USG_PN073-tdbcandidat_6408B42F17FC872440D4FF01BA6BAB16999CD903772C528808D1E6FA2B585CF2%26client_id%3DUSG_PN073-tdbcandidat_6408B42F17FC872440D4FF01BA6BAB16999CD903772C528808D1E6FA2B585CF2%26state%3Dj7b8AU3pPsqyBIDS%26nonce%3DZcYCzQvnLHtRRp2C%26redirect_uri%3Dhttps%253A%252F%252Fcandidat.pole-emploi.fr%252Fespacepersonnel%252F#login/")
username = browser.find_element_by_id("identifiant")
username.send_keys("maxence.vialat")
button2 = browser.find_element_by_id("submit")
button2.click()
password = browser.find_element_by_id("password")
password.send_keys("MOT DE PASSE")
button3 = browser.find_element_by_id("submit")
button3.click()
browser.get("https://authentification-candidat.pole-emploi.fr/compte/redirigervers?url=https://actualisation-authent.pole-emploi.fr/acces.htm&actu=true&actuCalculee=true")
time.sleep(3)
browser.get("https://actualisation-authent.pole-emploi.fr/WebUnidialog/AC/declareSituPage01.htm?flashLu=oui")
time.sleep(3)
button4 = browser.find_element_by_id("formationNon")
button4.click()
actions = ActionChains(browser) 
actions.send_keys(Keys.ENTER)
actions.perform()
button5 = browser.find_element_by_id("blocTravail-close")
button5.click()
button6 = browser.find_element_by_id("blocStage-close")
button6.click()
button7 = browser.find_element_by_id("blocMaladie-close")
button7.click()
button8 = browser.find_element_by_id("blocRetraite-close")
button8.click()
button9 = browser.find_element_by_id("blocInvalidite-close")
button9.click()
button10 = browser.find_element_by_id("blocRecherche-close")
button10.click()
time.sleep(2) 
actions.send_keys(Keys.ENTER)
actions.perform()
time.sleep(3)
actions.send_keys(Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB,Keys.TAB)
actions.perform()
time.sleep(1)
actions.send_keys(Keys.ENTER)
actions.perform()